export const RUNNING = "running"
export const FINISHED="finished"
export const REPAIRED="repaired"
export const IDLE="idle"
export const ERRORED = "errored"
export const MICROSCOPE = "microscope"
export const MEASUREMENT = "measurement"